export const copy = {
  appName: { sw: 'Safari Shule', en: 'School Journey' },
  play: { sw: 'Cheza', en: 'Play' },
  home: { sw: 'Nyumbani', en: 'Home' },
  test: { sw: 'Jaribio la Nyota', en: 'Star Test' },
  parent: { sw: 'Wazazi', en: 'Parents' },
  stars: { sw: 'Nyota', en: 'Stars' },
  chooseZone: { sw: 'Chagua mahali', en: 'Choose a place' },
  sokoni: { sw: 'Sokoni', en: 'Market' },
  bahari: { sw: 'Bahari', en: 'Coast' },
  pori: { sw: 'Pori', en: 'Savanna' },
  nyumbani: { sw: 'Nyumbani', en: 'Home' },
  shuleni: { sw: 'Shuleni', en: 'School' },
  hesabu: { sw: 'Hesabu', en: 'Numbers' },
  maneno: { sw: 'Maneno', en: 'Words' },
  duniaYetu: { sw: 'Dunia Yetu', en: 'Our World' },
  count: { sw: 'Hesabu vitu. Gusa namba sahihi.', en: 'Count the objects. Tap the right number.' },
  shape: { sw: 'Tafuta umbo linalofanana.', en: 'Find the matching shape.' },
  animal: { sw: 'Gusa mnyama sahihi.', en: 'Tap the right animal.' },
  letter: { sw: 'Gusa herufi sahihi.', en: 'Tap the right letter.' },
  world: { sw: 'Gusa jibu sahihi.', en: 'Tap the right answer.' },
  time: { sw: 'Saa inaonyesha muda gani?', en: 'What time does the clock show?' },
  add: { sw: 'Jumlisha vitu vyote. Gusa namba.', en: 'Add all the objects. Tap the number.' },
  findGiraffe: { sw: 'Twiga ni yupi?', en: 'Which one is the giraffe?' },
  findElephant: { sw: 'Tembo ni yupi?', en: 'Which one is the elephant?' },
  findZebra: { sw: 'Pundamilia ni yupi?', en: 'Which one is the zebra?' },
  findMother: { sw: 'Mama ni yupi?', en: 'Which one is mother?' },
  findFather: { sw: 'Baba ni yupi?', en: 'Which one is father?' },
  nextDay: { sw: 'Baada ya Jumatatu ni siku gani?', en: 'Which day comes after Monday?' },
  monday: { sw: 'Jumatatu', en: 'Monday' },
  tuesday: { sw: 'Jumanne', en: 'Tuesday' },
  wednesday: { sw: 'Jumatano', en: 'Wednesday' },
  correct: { sw: 'Hongera! Nyota moja!', en: 'Well done! One star!' },
  retry: { sw: 'Jaribu tena.', en: 'Try again.' },
  next: { sw: 'Endelea', en: 'Next' },
  done: { sw: 'Umefanya vizuri!', en: 'You did well!' },
  break: { sw: 'Twende tupumzike.', en: "Let's take a break." },
  back: { sw: 'Rudi', en: 'Back' },
  jump: { sw: 'Ruka-Lugha', en: 'Language Jump' },
  jumpHelp: { sw: 'Badilisha lugha inayoanza kila swali.', en: 'Alternate the leading language for each prompt.' },
  memory: { sw: 'Kumbuka!', en: 'Remember!' },
  memoryPrompt: { sw: 'Tafuta picha mbili zinazofanana.', en: 'Find two matching pictures.' },
  sort: { sw: 'Rangi Zangu', en: 'My Colours' },
  sortColor: { sw: 'Chagua ganda la rangi sawa.', en: 'Choose the shell with the same colour.' },
  sortSize: { sw: 'Sasa chagua ganda kubwa.', en: 'Now choose the big shell.' },
  build: { sw: 'Jenga la Vijiji', en: 'Build a Village' },
  buildPrompt: { sw: 'Gusa kujenga kijiji chako.', en: 'Tap to build your village.' },
  villageMission: { sw: 'Dhamira ya Kijiji', en: 'Village Mission' },
  villageGoal: { sw: 'Jenga nyumba 2, mti 1 na shamba 1.', en: 'Build 2 homes, 1 tree and 1 field.' },
  villageReady: { sw: 'Kijiji kiko tayari!', en: 'The village is ready!' },
  reset: { sw: 'Anza upya', en: 'Reset' },
  finishVillage: { sw: 'Maliza kijiji', en: 'Finish village' },
  stopGo: { sw: 'Simama/Kaa', en: 'Stop/Go' },
  stop: { sw: 'Simama! Subiri.', en: 'Stop! Wait.' },
  go: { sw: 'Kaa! Gusa duara.', en: 'Go! Tap the circle.' },
  reactionRun: { sw: 'Mbio za Mwitikio', en: 'Reaction Run' },
  reactionHelp: { sw: 'Subiri nyekundu. Gusa kijani haraka!', en: 'Wait on red. Tap green quickly!' },
  tooSoon: { sw: 'Mapema sana! Subiri kijani.', en: 'Too soon! Wait for green.' },
  greatMove: { sw: 'Vizuri! Endelea!', en: 'Great move! Keep going!' },
  parentGate: { sw: 'Kwa watu wazima', en: 'For grown-ups' },
  gatePrompt: { sw: 'Jibu swali la hesabu ili kuendelea.', en: 'Solve the sum to continue.' },
  gateWrong: { sw: 'Jibu si sahihi.', en: 'That answer is not right.' },
  dashboard: { sw: 'Ripoti ya mzazi', en: 'Parent dashboard' },
  settings: { sw: 'Mipangilio', en: 'Settings' },
  privacy: { sw: 'Futa maendeleo ya kifaa', en: 'Delete device progress' },
  export: { sw: 'Toa data', en: 'Export data' },
  purchase: { sw: 'Vitu vya ziada vya mapambo', en: 'Optional cosmetic extras' },
  trial: { sw: 'Jaribio la siku 3. Kisha $2.99 kila wiki, hujisasisha isipoghairiwa.', en: '3-day free trial. Then $2.99 each week, auto-renews unless canceled.' },
  lifetime: { sw: '$19.99 mara moja. Hakuna malipo mengine.', en: '$19.99 once. No further charges.' },
  selectPlan: { sw: 'Chagua mpango', en: 'Choose a plan' },
  manage: { sw: 'Dhibiti au ghairi usajili', en: 'Manage or cancel subscription' },
  restore: { sw: 'Rejesha manunuzi', en: 'Restore purchases' },
  storeUnavailable: { sw: 'Duka halipatikani sasa. Jaribu baadaye.', en: 'Store unavailable. Try later.' },
  reminder: { sw: 'Jaribio lako litakuwa la kulipia hivi karibuni. Ghairi dukani ikiwa hutaki kuendelea.', en: 'Your trial will become paid soon. Cancel in the store if you do not want to continue.' },
  noAccessNeeded: { sw: 'Masomo yote yako wazi bila malipo.', en: 'All learning games remain free.' },
  savedError: { sw: 'Hatukuweza kuhifadhi sasa.', en: 'Could not save just now.' },
  language: { sw: 'Lugha ya kwanza', en: 'First language' },
  volume: { sw: 'Sauti', en: 'Volume' },
  minutes: { sw: 'Dakika za mapumziko', en: 'Break reminder minutes' },
  report: { sw: 'Nyota zako', en: 'Your stars' },
  zero: { sw: 'Cheza tena!', en: 'Play again!' },
  unlock: { sw: 'Nyota za mapambo', en: 'Cosmetic stars' },
  audioMissing: { sw: 'Sauti haipatikani.', en: 'Audio unavailable.' },
  productUnavailable: { sw: 'Bidhaa haipatikani dukani sasa.', en: 'Product is unavailable in the store.' },
  purchaseNotReady: { sw: 'Manunuzi hayajawashwa bado.', en: 'Purchases are not enabled yet.' },
  choose: { sw: 'Chagua', en: 'Choose' },
  allDone: { sw: 'Jaribio limekamilika!', en: 'Test complete!' },
} as const;

export type CopyKey = keyof typeof copy;
export type Language = 'sw' | 'en';
export function pair(key: CopyKey, primary: Language) {
  const secondary = primary === 'sw' ? 'en' : 'sw';
  return { primary: copy[key][primary], secondary: copy[key][secondary] };
}

export type Zone = 'sokoni' | 'bahari' | 'pori' | 'nyumbani' | 'shuleni';
export const zones: { id: Zone; symbol: string; tint: string }[] = [
  { id: 'sokoni', symbol: '🍌', tint: '#F5C760' },
  { id: 'bahari', symbol: '🐚', tint: '#76C7CE' },
  { id: 'pori', symbol: '🦒', tint: '#E8AA6D' },
  { id: 'nyumbani', symbol: '🏠', tint: '#DAA6A0' },
  { id: 'shuleni', symbol: '📚', tint: '#A6C9A2' },
];
